# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18D6JsB4pOSEWyOiiq8BGgPWsPvnGESIu
"""

'''
Faça um programa em Python que leia o arquivo binário chamado "dados-funcionario.bin" e guarde o seu conteúdo em uma classe descrita abaixo. O primeiro dado contém a quantidade de registro e o resto do arquivo contém os objetos da classe Funcionario. O seu programa deverá ler esse arquivo binário, calcular e então imprimir quantos registros tem no total, a quantidade de homens, a quantidade de mulheres, a média de salário total de todos os funcionários, a média de salário de todos os homens e por fim, a média de salário de todas as mulheres. Use duas casas decimais para imprimir as médias de salário.

class Funcionario (object):
    def __init__(self, nome, idade, sexo, salario):
        self.nome = nome
        self.idade = idade
        self.sexo = sexo
        self.salario = salario
'''



import urllib.request
import pickle
class Funcionario (object): 
    def __init__(self, nome, idade, sexo, salario):
        self.nome = nome
        self.idade = idade
        self.sexo = sexo
        self.salario = salario

requisicao = urllib.request.urlopen('https://filebin.net/39u5bf9yqeybbma9/dados-funcionario.bin').read()

with open('arquivo', 'wb') as output:
    output.write(requisicao)
mulheres = 0
homens = 0
salario_mulheres = 0 # f
salario_homens = 0 # m
salario_total = 0
total = 0
with open('arquivo', 'rb') as arquivo:
    numero_registros = pickle.load(arquivo)
    for i in range(6):
         objeto = pickle.load(arquivo)
         total += 1      
         salario_total += objeto.salario
         if objeto.sexo == 'f':
             mulheres += 1
             salario_mulheres += objeto.salario
         else:
             homens += 1
             salario_homens += objeto.salario

print(f'{total} {mulheres} {homens} {salario_total/total:.2f} {salario_homens/homens:.2f} {salario_mulheres/mulheres:.2f}')

arquivo.close()