# -*- coding: utf-8 -*-
"""Dicionarios - Pop Item Agenda Telefonica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wrc0pgkaPu8NfRAHkiafV3GYktusBcbX
"""

#Dado um número de contatos N e N tuplas de linha onde o primeiro termo é o nome e o segundo o telefone. Crie um dicionario e mostre seu desempilhamento.

n_tuplas = int(input())

dicionario = dict()
for i in range(n_tuplas):
  dicionario.update({i : tuple(input().split())})


for values in range(n_tuplas -1,-1,-1):
  print(dicionario.get(values))