# -*- coding: utf-8 -*-
"""Dicionários - Mesclagem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16dJy4y0j2pbPMcOYCXCFo5Q0Vy-3DyP3
"""

'''
Dado 4 linhas, onde as duas primeiras são os nomes e telefones de uma agenda. E as duas ultimas linhas são os nomes e telefones de uma segunda agenda. Monte um dicionario e mostre em tela a primeira agenda, a segunda agenda e a mesclagem (união[Agenda2 + Agenda1]) da segunda agenda com a primeira.
'''

#dados do usario:

nome_1 = input().strip().split(',')
num_1 = input().strip().split(',')
nome_2 = input().strip().split(',')
num_2 = input().strip().split(',')

# Já criado
def criar_agenda(nomes,numeros):
  agenda = {}
  for i in range(len(nomes)):
    agenda.update({nomes[i]: int(numeros[i])})
  return agenda


def uniao_dicionario(dic1,dic2):
 dic = dic1.copy() 
 dic.update(dic2)
 return dic





dicionario_1 = criar_agenda(nome_1,num_1)
dicionario_2 =  criar_agenda(nome_2,num_2)
dicionario_unido = uniao_dicionario(dicionario_2,dicionario_1)

print('Agenda 1',dicionario_1 , sep='\n')
print('Agenda 2',dicionario_2, sep='\n')
print('Agenda Mesclada',dicionario_unido,sep='\n')