# -*- coding: utf-8 -*-
"""tabuada.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rppp3zcYQh7pB3CL42PjS1Jh8H5JD_GC

Faça um programa que mostre a tabuada (do 0 até o 10) de um determinado número.

Entrada: Um número inteiro

Saída: A tabuada do número.
"""

N = int(input())
tabuada = []

for i in range (0,11):
  tabuada.append(i*N)

for x in tabuada:
    print(x, end=' ')