# -*- coding: utf-8 -*-
"""Divisores de N.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pNdtpI_U0JJZ7cegdHPxAEDWzKVjB1aM

Desenvolva um algoritmo que leia um número N inteiro positivo e escreva os divisores desse valor.

Entrada: Um inteiro N, sendo N >= 0

Saída: Um linha para cada divisor do número N em ordem decrescente.
"""

N = int(input())
divisiores = []

for i in range(1,N+1):
  if N % i == 0:
    print(N//i)