# -*- coding: utf-8 -*-
"""menornumero.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Y6U58F2mLek6SwniWauz_dHNsyl-3cz

Faça um programa que dado um número X e 10 números inteiros, imprima quantos números são menores que X.

Entrada: Um número inteiro X seguido de 10 números inteiros

Saída: A quantidade de números menores que X

Dica: Para ler a lista de valores utilize lista = list(map(int,input().split()))
"""

N = int(input())
lista_de_numeros = lista = list(map(int,input().split()))

contador = 0

for i in lista_de_numeros:
  if i < N:
    contador = contador + 1

print(contador)