# -*- coding: utf-8 -*-
"""Dias dos meses

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-eJgM9dUhoa8kLm2sRTcIgwo38yyvJWd

Faça um programa que dado o nome do mês, entregue o número de dias que ele tem (calendário 2021).
"""

mes = str(input())
meses_31_dias = ('janeiro','março','maio','julho','agosto','outubro','dezembro')

if mes in meses_31_dias:
    dias = 31
elif mes == 'fevereiro':
    dias = 28
else:
    dias = 30
print(dias)