# -*- coding: utf-8 -*-
"""Exceções - Entrada.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13HWLwXrHWxsJmSmA3BCTsWsgcIaKezlv
"""
'''
Observe o programa abaixo:

a = int(input())

print("O número digitado foi:", a)
Reescreva esse código de uma forma com que ele seja capaz de tratar a inserção de um caractere por parte do usuário.
'''

try:                       # Um bloco de try/except que trata ValueError
  a = int(input())
  print(f"O número digitado foi: {a}") 
except(ValueError):                             # Se int(alguma coisa que não converte em inteiro) teriamos Value error , mas tratamos para imprimir "Entrada invalida"
  print('Entrada Inválida.')