# -*- coding: utf-8 -*-
"""Exceções - Raiz quadrada.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15KhBRvYPlJNOMd9IqJlibgiKcHf01fhw
"""

#Faça um programa que calcule a raiz quadrada de um número n e trate os casos em que n < 0.



num  = int(input())
# Uma função que retorna a raiz quadrada de um numero caso positvo , caso contrario cria um ValueError
def raiz_quadrada (numero):
  if numero <0:
    raise ValueError('Erro no cálculo da raiz quadrada pois número é negativo.')
  return int(numero ** 0.5)

# em seguidas tratamos a função em um bloco de try / except

try:
  print(raiz_quadrada(num))
except ValueError as error:
  print(error)