# -*- coding: utf-8 -*-
"""Exceções - Divisão por zero.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1inPd6-5Xy4rERJl2m6Q2YxQhP7vyPhZT
"""
#Faça um programa que calcule a divisão de dois números m e n e trate os casos em que n = 0.


# Coletando dados do usuario e armazenando em uma lista
num_raw_format = input().split()
num_list = [int(i) for i in num_raw_format]

# Criei uma função que divide os numeros e trata a excesao ZeroDivisionError
def divisao (lista_de_dois_numeros):
  try:
    print(int(num_list[0]/num_list[1]))      
  except(ZeroDivisionError):
    print('Erro: divisão por 0.')

divisao(num_list) # chamamos essa função