# -*- coding: utf-8 -*-
"""função planetas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18PmLrD342duiXp8uQfmpZXjHUmcjDeR0
"""

'''
Você, um jovem universitário mochileiro espacial, está viajando pelo sistema solar. Você está com fome e, como todo bom universitário, só tem dinheiro para comer no bandejão.

Portanto, seria muito útil você saber quanto tempo sua viagem até cada um dos planetas durará em termos dos dias de cada planeta, já que cada um tem uma rotação diferente. Assim, você poderia traçar a melhor rota para pegar um bandejão ainda aberto, seja na Terra, em Júpiter, em Vênus ou em Mercúrio (nos outros planetas você sabe que terá picadinho).

Para tanto, você fará um programa que receberá um inteiro contendo o total de segundos gasto na viagem e uma string contendo o nome do planeta de destino.

Então, seu programa deverá calcular quantos dias, horas, minutos e segundos são equivalentes à passagem desse tempo em segundos no planeta destino. Como um bom estudante, você fará uma função que receberá todos esses parâmetros e, calculado o resultado, irá imprimi-lo na main do seu programa.

Vamos arredondar o dia terrestre para 24 horas (você sabe que ele dura 23 horas e 56 minutos, mas os terráqueos gostam de simplificar).

O dia em Vênus equivale a 243 dias terrestres.
O dia em Mercúrio equivale a 58 dias e 16 horas terrestes.
O dia em Júpiter equivale a 9 horas e 56 minutos terrestres (Cuidado, esse vai ser um pouco mais difícil calcular!). Obs: Todos os nomes de planetas serão fornecidos sem acentos e com a primeira letra maiúscula.
Saída desejada:

print(f-'{valor1} segundos no planeta {nomePlaneta} equivalem a:')
print(f-'{valor2} dias, {valor3} horas, {valor4} minutos e {valor5} segundos')
'''

# Devemos criar uma função que recebe planeta e tempo e utiliza condiçoes em planeta
s, planeta = input().split()
s = int(s)

def f1(p,t):
  if p == 'Terra':    
    dias = t // (24*60*60)
    horas = (t - dias*(24*60*60)) // (60*60)
    minutos = (t - (dias*(24*60*60) + horas*(60*60))) // 60
    segundos = t - (dias*(24*60*60) + horas*(60*60)  + minutos*60)                                                             # planeta == terra retorna valores usais
    print(f"{t} segundos no planeta {p} equivalem a:")          
    print(f"{dias} dias, {horas} horas, {minutos} minutos e {segundos} segundos")
  elif p == 'Jupiter':
    dias_jupiter = t // (9*60*60 + 56*60) 
    horas_jupiter = t % (9*60*60 + 56*60) // (60*60)
    minutos_jupiter = (t % (9*60*60 + 56*60) - horas_jupiter*60*60) // 60
    segundos_jupiter = (t % (9*60*60 + 56*60) - horas_jupiter*60*60 - minutos_jupiter*60)
    print(f"{t} segundos no planeta {p} equivalem a:")          
    print(f"{dias_jupiter} dias, {horas_jupiter} horas, {minutos_jupiter} minutos e {segundos_jupiter} segundos")
  elif p == 'Mercurio':
    dias_mercurio = t // (58*24*60*60 + 16*60*60) 
    horas_mercurio = t % (58*24*60*60 + 16*60*60) // (60*60)
    minutos_mercurio = (t % (58*24*60*60 + 16*60*60) - horas_mercurio*60*60) // 60
    segundos_mercurio = (t % (58*24*60*60 + 16*60*60) - horas_mercurio*60*60 - minutos_mercurio*60)
    print(f"{t} segundos no planeta {p} equivalem a:")          
    print(f"{dias_mercurio} dias, {horas_mercurio} horas, {minutos_mercurio} minutos e {segundos_mercurio} segundos")
  elif p == 'Venus':
    dias_venus = t // (243*24*60*60) 
    horas_venus = t % (243*24*60*60) // (60*60)
    minutos_venus = (t % (243*24*60*60) - horas_venus*60*60) // 60
    segundos_venus = (t % (243*24*60*60) - horas_venus*60*60 - minutos_venus*60)
    print(f"{t} segundos no planeta {p} equivalem a:")          
    print(f"{dias_venus} dias, {horas_venus} horas, {minutos_venus} minutos e {segundos_venus} segundos")





f1(p = planeta,t = s)

