# -*- coding: utf-8 -*-
"""função angulos de triangulo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FKlEbufSyd_Ac03RVH6JpwRC1hP49HqB


Desenvolva um programa onde o usuário fornece as medidas dos três ângulos de um triângulo e o tipo de triângulo (agudo, obtuso ou retângulo) é escrito na tela. Lembre-se, você deve verificar também o critério de formação de triângulo, onde a soma dos ângulos internos de um triângulo deve ser 180 graus. Logo, o programa deve ter duas funções: uma função angulotriangulo() que recebe os ângulos e imprime o tipo de triângulo e uma função ehtriangulo() que recebe os ângulos e retorna verdadeiro se for triângulo e falso, caso contrário.

Dica: Use os seguintes formatadores de print:

print("Triangulo retangulo")
print("Triangulo obtuso")
print("Triangulo agudo")
print ("Valores nao formam um triangulo")
"""

# Input

A = float(input())
B = float(input())
C = float(input())



# Função que verifica se é triangulo

def ehtriangulo(a1,a2,a3):
  if float(a1) + float(a2) + float(a3) == 180:
    return True
  else:
    return False
# Função que verifica os angulos
def angulotriangulo(a1,a2,a3):
  if ehtriangulo(A,B,C) == False:
    print("Valores nao formam um triangulo")
  else:
      if a1 == 90 or  a2 == 90 or a3 == 90:
        print('Triangulo retangulo')
      elif a1 > 90 or  a2 > 90 or a3 > 90:
        print('Triangulo obtuso')
      else:
        print('Triangulo agudo')


# Chamar as funções
ehtriangulo(A,B,C)
angulotriangulo(A,B,C)