# -*- coding: utf-8 -*-
"""Função-divisores.ipynb

Automatically generated by Colaboratory.

Original file is located at

    https://colab.research.google.com/drive/1DdGIHj2HV7UBuvxuS4-H0IJWs0tx7Voz

Função - Divisores
Crie uma função que use um número inteiro (n> 1) e retorne uma matriz com todos os divisores desse mesmo número (com exceção do 1 e do próprio número), do menor para o maior.

Caso o número seja primo, retorne a string eh primo.
"""

#lista = []
numero = int(input())
def divisores(n):
  lista = []
  for i in range(2,n):
    if n % i == 0:
      lista.append(i)
  if len(lista) ==0:
    print(f"{n} eh primo")
  else:
    print(lista)

  


divisores(numero)