# -*- coding: utf-8 -*-
"""Função triangulo via lados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z5j1bPmFtyEJNtsmBkpGvQTcv9qDGrK5
"""

#Breve comentário a estrutura já foi feita em um  exerc anterior basta transformar em função
x = float(input())
y = float(input())
z = float(input())

def ehtriangulo(a,b,c):
  if a < c+b and b < c +a and c < b +a:
    return True
  else:
    return False


#A logica foi feita em outro exerc
def classificatriangulo(e,f,g):
  if ehtriangulo(e,f,g) == False:
    print('Valores nao formam um triangulo')
  else:
      if e == f and e == g:              # Se E é igual a f  e  E é igual a g , g é igual a F.
        print('Triangulo Equilatero')
      elif (e==f) or (e==g) or (f==z):  # Um dos lados é iguais , mas não todos. Essa estrutura lógica considera  o equilatero igual o isoceles. Contudo, para reduzir o codigo,sabendo que o python executa  if elif else , nessa ordem,não precisamos preocupar com o resultado.Embora a lógica esteja errada 
          print('Triangulo Isosceles')
      else:
          print("Triangulo Escaleno")





ehtriangulo(x,y,z)
classificatriangulo(x,y,z)