# -*- coding: utf-8 -*-
"""Listas e Tuplas - Maior e menor palavra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DCdxgN3FROodmYvccO7cRgsa_Ki3QhtC
"""

'''
Desenvolva um algoritmo que leia uma frase e encontre a maior e a menor palavra nessa frase. Imprima as palavras encontradas. Se houver mais de uma palavra com o menor ou maior tamanho, imprimir a primeira que aparece na frase.

Entrada: Uma frase

Saída: Duas linhas, a menor e a maior palavra, respectivamente
'''
frase = input().split()                 # recebe dados do usuario em uma lista
tamanho = [len(i) for i in frase]         # cria uma lista com o tamanho
tamanho.sort()  # Ordena usando um metodo do python 

candidatos_a_max = [i for i in frase if len(i) ==  tamanho[len(tamanho) - 1]]    # faz uma lista  das maiores palavras
candidatos_a_min= [i for i in frase if len(i) ==  tamanho[0]]   # faz uma lista com as palavras de menores palavras

#devemos lembrar que o for pecorre a lista frase do inicio ao fim isso é lista[0] , lista [1] .... lista[len(lista) -1]
#observe que os candidatos a maximo,por consequencia disso,estão em ordem crescente em relação a posição que aparece na frase
#Essa é uma situação que um teste de mesa é útil para visualizar a lógica do código.
print(candidatos_a_min[0])
print(candidatos_a_max[0])