# -*- coding: utf-8 -*-
"""Inversão listas e tuplas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TvT0cZygIdRjauHUX3hB_yivqxK5Cmcn
"""

'''
Desenvolva um algoritmo que leia um conjunto de 20 valores inteiros, guarde-os em uma lista e troque a sua ordem. Ou seja, o programa deve trocar lista[0] com lista[19], lista[1] com lista[18] e assim por diante.

Entrada: Uma linha com 20 números inteiros.

Saida: Os mesmos 20 números em ordem inversa, um por linha
'''
# Já invertemos um vetor recursivamente em outra questão. Como , nesse caso, não há restrição quanto aos métodos vou utilizar o que é nativo do python .


# Recebe a entrada 
lista_de_numeros = [int (i) for i in input().split()]       # Entrada: Uma linha com 20 números inteiros , não 20 strings
lista_de_numeros.reverse()       # reverse altera lista de numeros 
for j in lista_de_numeros:
  print(j)