# -*- coding: utf-8 -*-
"""ciclista formatado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xg8TDhvqDx4lvHRJNI-BmSqS58zZ2O1P
"""


'''

Implemente o Diagrama de Classes em anexo. Em seguida, dado o nome de um atleta criar um objeto do tipo TriAtleta e imprima o mesmo.


'''

nome = input()
class Atleta:
  def __init__(self,nome):
    self.nome = nome
  def get_nome(self):
    return self.nome

class Corredor(Atleta):
  def __init__(self,nome):
     Atleta.__init__(self,nome)   
  def correr(self):
    return f"Corredor {self.nome} correndo"

class Nadador(Atleta):
  def __init__(self,nome):
     Atleta.__init__(self,nome)   
  def nadar(self):
    return f"Nadador {self.nome} nadando"

class Ciclista(Atleta):
  def __init__(self,nome):
     Atleta.__init__(self,nome)   
  def pedalar(self):
    return f"Ciclista {self.nome} pedalando"    

class TriAtleta(Corredor,Nadador,Ciclista):
  def __init__(self,name):
    Corredor.__init__(self,name) 
    Nadador.__init__(self,name) 
    Ciclista.__init__(self,name) 
  def __str__(self):
    return self.correr() + '\n' + self.nadar() + '\n' + self.pedalar()

print(TriAtleta(nome))