# -*- coding: utf-8 -*-
"""fatorial recurivo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jjOssnKU53vtlk-mrSXq8FYfgeGeegdX
"""

numero = int(input())
def fatorial (n):
  if n == 0 or n  == 1:
    return 1
  else:
     return n*fatorial(n-1)

print(fatorial(numero))