# -*- coding: utf-8 -*-
"""Recursão - Potência.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qi3NQbAluVpwnmSQVS7CewhaGfke2G9G
"""

base = int(input())
expoente = int(input())
def potencia(base , expoente):
  if expoente == 0:
    return 1                     # aqui é a condição de
  else:
    return base*potencia(base,expoente - 1)

def potencia_negativa(base , expoente):
  if expoente == 0:
    return 1                     # aqui é a condição de
  else:
    return 1/base*potencia_negativa(base,expoente + 1)


if expoente > 0:
  print(potencia(base,expoente))
else:
  print(potencia_negativa(base,expoente))