# -*- coding: utf-8 -*-
"""Recursão - Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s8hHVsIsgrBxkCfAsvuYMcusODKIK-5W
"""

numero = int(input())
def fibonacci(n):
  if n <= 1:
    return n                     # tinha me enrolado aqui ....
  else:
    return(fibonacci(n-1)+ fibonacci(n-2))                       # veja https://pt.wikipedia.org/wiki/Sequ%C3%AAncia_de_Fibonacci
                                                                 # so escrevi a função aqui . 

print(fibonacci(numero))