# -*- coding: utf-8 -*-
"""polidromo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dTEpriWw20uSjRX0rtXBeo6itu8W9RrE

Desenvolva um algoritmo que leia uma sentença e determine se a mesma é ou não é de um palíndromo. Palíndromo: palavras, frases, ou números que preservam seu valor independentemente de serem lidos da esquerda para direita ou da direita para a esquerda. Exemplos: ARARA, AMOR A ROMA, 12321 são palíndromos.

Dica: use o metódo upper() para converter todos os caracteres para maiúsculos e facilitar a comparação entre caracteres minúsculos e maiúsculos.

Entrada: Uma string. A sentença para ser analisada.

Saida: O seu programa deve imprimir "SIM" (sem aspas) se a sentença for um palíndromo e "NAO" caso contrário.
"""

variavel = str(input())
variavel = variavel.upper()



if variavel[::-1] == variavel[:]:
  print('SIM')
else:
  print('NAO')