# -*- coding: utf-8 -*-
"""vogais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vzl2AWr9VNK5ME1GbLvLjsUJY3m9bpHG

Faça um programa que leia um vetor de caracteres, gere e imprima um outro vetor onde as vogais, do primeiro vetor, sejam substituídas pelo carácter ’*’.

Entrada: Um vetor de caracteres

Saída: Um vetor de caracteres com as vogais substituídas por '*'
"""



string = str(input())
vogais = ['a','e','i','o','u','A',"E","I",'O',"U"]
sem_vogal = []

for vogal in vogais:
 if vogal in string:
   string = string.replace(vogal,'*')


print(string)