# -*- coding: utf-8 -*-
"""remove o caracter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13thLf4Rw1UckTpZw-mOhi0FR9y_-Pm3_ 

Desenvolva um algoritmo que leia uma palavra e um caractere, e apague todas as ocorrências desse caractere na palavra.

Dica: Pesquise sobre o método translate() em python

Entrada: 1 palavra e 1 caractere

Saída: Uma palavra sem o caractere digitado
"""

palavra = str(input())
caracter = str(input())
caracter_grande = caracter.capitalize()

x = palavra.replace(caracter,'')
x = x.replace(caracter_grande,'')

print(x)